// src/app/layout.tsx
import type { Metadata } from "next";
import type React from "react";
import "./globals.css";
import RootShell from "./RootShell";

export const metadata: Metadata = {
  title: "Catneko-0422",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <RootShell>{children}</RootShell>
      </body>
    </html>
  );
}
